### ISSUE TITLE
Database connection string is hard-coded

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#134]
Only the database password is injected as environment variable, but the actual database connection string is hard-coded inside the code.

Which means that the app couldn't be used with a different database unless modifying the code.

**Comment by edipetres** [comment]
@buep can you check if this is something we want our project to have

**Comment by buep** [comment]
I would say we need all these hard-coding string to be in some kind of configuration file, that is applied to the deployment... that way you can also very easily make two different deployment, one to test and one to prod but just using another configuration file.

So please spin out some issues for this to work.

**Comment by edipetres** [comment]
@buep Yes - little correction - it is not hard-coded into the code, but the database connection string actually sits in a configuration file, just not on the root of the project (but in `api/config/config.js`).

I think for deploying to testing and production environments the best would be to store it as an environment variable like we store the database password now. Then the testing pipeline could pass on the testing database URI, while the production step would run the Docker container with the production URI. Do you agree? :)

**Comment by buep** [comment]
Yes, let's do that for now then.

**Comment by edipetres** [comment]
Created issue #156 for this
