### ISSUE TITLE
Create AWS account for the release step

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#148]
Use Praqma main to create an account that can deploy the app as part of the pipeline.

**Comment by buep** [comment]
And document the roles, security policies, account name etc. so we know how to make one again.

**Comment by edipetres** [comment]
Added credentials to `it-administration`. Roles and security policies are not fixed yet. Will document once we settle on the bare minimum.

**Comment by buep** [comment]
Added #163 so we don't forget.
