### ISSUE TITLE
Dockerhub documentation to display Github README

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#150]
Add a step in the pipeline that will inject the README content of the repo to the Dockerhub repository that it pushes to

- point back to original README from the Dockerhub description

**Comment by buep** [comment]
This is not possible - unless we use dockerhub auto builds, there is no API to fill out details on a docker hub image programatically.

Best option is just to add a link to the repository in the short description to point to the project on github. That will not really have to be updated again.

**Comment by edipetres** [comment]
done:
https://hub.docker.com/r/praqma/questionnaire-engine/
