### ISSUE TITLE
Handle versioning in a separate configuration file

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#155]
Use a dedicated file for this. Could create a shell script that contains a var.
`VERSION=0.1.2`
Sourcing this file will create the env var in the linux environment.
Append the build number as a 4th decimal: `0.1.2.145` or `0.1.2-145`

See [semver.org/](https://semver.org/) for details.

**Comment by edipetres** [comment]
CircleCI handles environment variables in a way that I could not append the build number to the version. Running `source version.sh` will define the bash var $VERSION but the upcoming command to append the $BUILD_NUM to it will fail because the $VERSION is not available in this scope already.

Created issue #157 to fix this

**Comment by buep** [comment]
I think the problem is that every line in your circle ci script is executed in a new shell sessions, so if you export something in line x and try to use it in line Y it is not the same session, thus not available.

So try to do it as a oneliner... or wrap it in a script you execute instead.
