### ISSUE TITLE
Deployment step problems

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#162]
## Problem
Every time our CI pipeline releases a new Docker image we want to have that image deployed to a server and it's IP redirected to our domain name (e.g. `questionnaire.praqma.com`).

### 1. [Fargate CLI](https://github.com/jpignata/fargate)
This tool simplifies deployment to AWS ECS (read more below) and I used it successfully in the past to deploy the questionnaire-engine. The problem with this tool is that it creates a new service every time and deploys the container to a new server, instead of updating the old one. Could spend some time researching if the update is even possible with this tool. If so, this could be the simplest one-liner shell script to deploy the container online. But with my current knowledge of this tool, I'm not sure it can do that. Also, I don't know if we can do routing with this tool - if we can get a static IP each time it deploys we can have our domain redirect to it, but right now it creates a new IP each time we deploy.

> fargate is a command-line interface to deploy containers to AWS Fargate that
makes it easy to run containers in AWS as one-off tasks or managed, highly
available services secured by free TLS certificates. It bundles the power of AWS
including Amazon Elastic Container Service (ECS), Amazon Elastic Container
Registry (ECR), Elastic Load Balancing, AWS Certificate Manager, Amazon
CloudWatch Logs, and Amazon Route 53 into an easy-to-use CLI.

### 2. AWS CLI 
The native CLI tool provided by AWS. Due to its support of programmatic access to all AWS services, it is a very heavy tool and I found it rather complex to use it for deployment, though it is certainly possible to update the deployed Docker image with this one.

### 3. Manual deployment
Using the web interface we can manually deploy and update (!) containers hosted on Dockerhub. If we plan to not have many releases this could be a solution, but again, it is a manual step and cannot be automated.

### 4. Docker Swarm
Next Friday (23 Feb) we have an intro to Docker Swarm. I am not familiar with this tool, but Praqma Academy has proven to provide great boot camps. It is one possible option too.

## Notes
I wanted to hear your feedback on this, @buep as I'm rather clueless on which is the best path to take. It was suggested to ask in the `#operations` channel, so if you give a go-ahead I can post this message there.

**Comment by buep** [comment]
> .. Also, I don't know if we can do routing with this tool - if we can get a static IP each time it deploys we can have our domain redirect to it, but right now it creates a new IP each time we deploy. ...

If you can just get the new IP address programmatically returned every time, another AWS CLI tool might be able to set up routing with that a input.

The fargate description you posted also mentions Route53, so I get it can do DNS stuff as well.


@edipetres there are all good considerations you have and a nice write-up. You're always welcome to just ask in our Operations channel.

I only veto the manual deployment - our deployment design is based on being automatically as we bundle content into deployable containers, thus there will be many updates.

I think fargate is a possibility... I couldn't either in a very very quick google search figure out how to redeploy, but they must have though of that.

Maybe asks our managed devops team.

By the way my comments around a `test` env for testin in #151 is very relevant for the above deployment configurations.
You need to be able to deploy several environments.

**Comment by edipetres** [comment]
moved to #164
