### ISSUE TITLE
Guarantee that services are pruned

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#172]

**Comment by edipetres** [comment]
I assigned this `must have` because we should not have unused services hanging around on AWS - it could be costly.

**Comment by buep** [comment]
Yes, please look into it :-)

**Comment by edipetres** [comment]
moving it to [`questionnaire-models`](https://github.com/Praqma/questionnaire-models/issues/2) as it belongs to that deployment
