### ISSUE TITLE
Change the name of this repo

### ISSUE THREAD

**Issue by lakruzz** [Praqma/questionnaire-engine#22]
We need to come up with a better name. This is Not (necessarily) about the Maturity model - it's a matrix-based questionnaire

Reference exist to [Praqma/questionnaire](https://github.com/Praqma/questionnaire) and to [Praqma/matrix-questionnaire](https://github.com/Praqma/matrix-questionnaire)

**Comment by buep** [comment]
The new name should support the vision in #60

**Comment by edipetres** [comment]
Repo name suggestions:
- `questionnaire-engine`
- `forms-engine`
