### ISSUE TITLE
Define and setup the development environment

### ISSUE THREAD

**Issue by lakruzz** [Praqma/questionnaire-engine#24]

**Comment by edipetres** [comment]
I need some help clarifying this task. I can Dockerise the node app locally, but does this issue require more?

**Comment by lakruzz** [comment]
More like what we were hacking here (see the commit on the issue)

lakruzz/MacAsCode#39

> What do I need on my PC to contribute to your code base.

@edipetres

**Comment by buep** [comment]
You only need a docker command and an IDE of your choise.

So this is mostly solved by the README documentation done in #25 I think.

You could explain how to get for example syntax highligthing in our own IDE configured... so you help me and Lars to get a nice IDE up and runing.
Should be doable in a few lines.
